### ISSUE TITLE
Change email regex

### ISSUE THREAD

**Issue by pyros2097** [playlyfe/themis#19]
Use the email regex from this [/^([\w_\.\-\+])+\@([\w\-]+\.)+([\w]{2,10})+$/;](https://github.com/regexps/regex-email/blob/master/index.js)
as the current regex does not allow undescores in email ids

**Comment by kumarharsh** [comment]
As per http://emailregex.com/

This is better:
```/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i```

**Comment by pyros2097** [comment]
I guess the second one is better... Someone better change it in themis and upgrade the version people are getting issues with this stuff

**Comment by kumarharsh** [comment]
This is fixed in f4bc33
