### ISSUE TITLE
Running benchmarks fails

### ISSUE THREAD

**Issue by Muscula** [playlyfe/themis#6]
I'm trying to run the benchmarks and get the error:
```
fs.js:654
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/allanebdrup/Dropbox/themis/benchmark/../test/jsonSchemaTestSuite/tests/draft4/'
    at Object.fs.readdirSync (fs.js:654:18)
    at readDirToObject (/Users/allanebdrup/Dropbox/themis/benchmark/tester.js:160:20)
    at Object.Tester.runDirectory (/Users/allanebdrup/Dropbox/themis/benchmark/tester.js:176:17)
    at Object.<anonymous> (/Users/allanebdrup/Dropbox/themis/benchmark/benchmark.js:115:8)
```
Seems the folder `test/jsonSchemaTestSuite` is missing from the repo. How do I get it?

**Comment by atrniv** [comment]
You can check it out from `https://github.com/json-schema/JSON-Schema-Test-Suite.git`

**Comment by Muscula** [comment]
cool. You should add it as a git submodule.
I'm trying to add `is-my-json-valid` and `jsck`to your benchmarks.

**Comment by atrniv** [comment]
I'm already in the process of adding them myself. IMJV definitely seems a lot faster, however I'll have to look at its internals and see if it's feasible to gain the same efficiency in Themis given its additional feature set. 

—
